### ISSUE TITLE
SOCK Proxy Support.

### ISSUE THREAD

**Issue by Doimatcuabautroi** [Snawoot/opera-proxy#15]
Please support not only bind as HTTP proxy, but Sock Proxy too

**Comment by Snawoot** [comment]
What is use case? Is there cases where applications support SOCKS proxies but do not support HTTP proxies? If so, what are these applications?

**Comment by Doimatcuabautroi** [comment]
Yeah, I want redirect all internet traffic go through tun/tap to sock proxy for "privacy" reason, for example: webrtc leak, dns leak, ...
https://github.com/eycorsican/go-tun2socks
https://github.com/ambrop72/badvpn

**Comment by Doimatcuabautroi** [comment]
![aaa](https://user-images.githubusercontent.com/18320809/135745980-6867d048-55ca-4307-9753-0ad9e2d45ca2.jpg)

**Comment by Doimatcuabautroi** [comment]
![aaa](https://user-images.githubusercontent.com/18320809/135746023-573c7afb-0848-4447-9a4e-ed22e552c268.jpg)

**Comment by Snawoot** [comment]
It will not work as expected. SOCKS proxies capable of forwarding UDP traffic with UDP ASSOCIATE command, while HTTP proxies are not. It is possible to create SOCKS5 socket listener for opera proxy, but for TCP only - there is no way to implement UDP ASSOCIATE for it because upstream proxies used by opera-proxy are HTTP(S) proxies.

About your privacy concerns, if you're using opera-proxy with browser, DNS leak will not happen - hostnames are on proxy server side, browser just issues CONNECT method with desired domain, not resolving it by itself. WebRTC can be disabled in browsers to prevent leak: https://whoer.net/blog/how-to-disable-webrtc-in-various-browsers/

Here is a good resource to test if leaks actually happening: https://browserleaks.com/ip
