### ISSUE TITLE
No virtual interface

### ISSUE THREAD

**Issue by dumbuser4557** [Snawoot/opera-proxy#36]
I'm trying to use opera-proxy with this program, which does support using a VPN:
https://github.com/lakinduakash/linux-wifi-hotspot

in the README file, it says "Select the virtual interface created by the VPN. In this case it is tun0"
but opera-proxy does not create a virtual interface

related to the problem:
https://github.com/lakinduakash/linux-wifi-hotspot/issues/307

**Comment by Snawoot** [comment]
Hello,

It doesn't create TUN adapter because it's not a VPN, it's a proxy. However, you can still redirect only TCP connections (but not UDP sessions) into opera-proxy with any of following transparent proxying software:
* [transocks](https://github.com/cybozu-go/transocks)
* [redsocks](https://github.com/darkk/redsocks)
* [glider](https://github.com/nadoo/glider)
* ... and many more

It should go like this: you add REDIRECT rule into iptables to send TCP connections from clients to port of transparent proxy (transocks/redsocks/glider) and this transparent proxy has to be set to use opera-proxy as an upstream proxy.

Not sure, how to set up your linux-wifi-hotspot instance, but probably few additional daemons and iptables rule won't hurt this installation. But my general recommendation would be to use some real VPN connection, because opera-proxy can't help you with forwarding DNS and other UDP traffic.
