### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by DsChauhan08** [Snawoot/opera-proxy#39]
I'm not able to understand how to use on android as it says. Care to explain?

**Comment by Snawoot** [comment]
Hi! It's a bit clumsy, but still possible.

1. Install some terminal emulator app like [Qute](https://play.google.com/store/apps/details?id=com.ddm.qute&hl=ru&gl=US)
2. Download opera-proxy binary to Android phone.
3. Run opera-proxy in that shell.

opera-proxy will accepting connections. However, you need to use it somehow. In order to redirect all connections into that proxy, you'll need some proxy client application for Android like Adguard or Clash or SagerNet or NekoBox. Also you'll need to exclude shell application (e.g. Qute) from list of applications rerouted to proxy otherwise opera-proxy's upstream connections will be looped back into itself.
