### ISSUE TITLE
Change geographic location in opera proxy for android

### ISSUE THREAD

**Issue by trimechee** [Snawoot/opera-proxy#42]
Hello, thank you again for this VPN :) 

 I have a question please, why opera does not protect its VPN i.e. why opera does not put a protection mechanism to prevent the use of its proxy outside of opera browser? or maybe there is ads when using this proxy so opera can finance its vpn ?

I have another question please: when using the Opera browser, the Opera browser automatically chooses the best VPN location for faster browsing, can Standalone Opera VPN client do this by choosing the default location? fastest geographic location automatically?

and also how we can choose the geographical location when we use opera-proxy for android because we cannot add command line arguments to the shortcut like in windows 10 os?  Thanks !

Another question please :  we know that opera was bought by a Chinese consortium in 2016, I do not accuse this company which is certainly honest but we know that the Chinese communist party likes to control and monitor people and likes to spy on people and imposes on Chinese companies to follow their orders, so is there a security risk when using opera proxy when for example the Chinese communist party orders opera to give out user passwords?

Another quetion please : hola -proxy  has option " peer proxies on residental IPs (consumer ISP) ", 

I read that the tuxler vpn

https://www.tuxlervpn.com/

  allows us to use the real IP addresses of users and if a malicious user takes our IP address and does illegal activity, we can be punished and go to prison....is it the same thing with hola proxy when we use hola -proxy has option " peer proxies on residential IPs" ? hola proxy allows people to use our real ip address ?

**Comment by Snawoot** [comment]
> I have a question please, why opera does not protect its VPN i.e. why opera does not put a protection mechanism to prevent the use of its proxy outside of opera browser? or maybe there is ads when using this proxy so opera can finance its vpn ?

They actually do protect it from unauthorized usage. There is a [login and password](https://github.com/Snawoot/opera-proxy/blob/9e7868d67a7db27bc8076f68a17f1a4701237980/main.go#L78-L79) required for interaction with their API, and sophisticated [digest authentication scheme](https://github.com/Snawoot/go-http-digest-auth-client) required to sign requests. But since these credentials are baked into Opera browser, it is possible to analyze compiled machine code and figure out how browser interacts with API to get access. But this is as much as they can do to provide public service in their software without user registration.

> I have another question please: when using the Opera browser, the Opera browser automatically chooses the best VPN location for faster browsing, can Standalone Opera VPN client do this by choosing the default location? fastest geographic location automatically?

If someone will implement this, I'll be glad to accept pull request. But in general they offer just three continents (America, Europe, Asia) and it's quite evident which is closer to you.

> and also how we can choose the geographical location when we use opera-proxy for android because we cannot add command line arguments to the shortcut like in windows 10 os? Thanks !

If you're running opera-proxy on Android using something like Termux, you can add command line parameters the same way after name of executable.

> Another question please : we know that opera was bought by a Chinese consortium in 2016, I do not accuse this company which is certainly honest but we know that the Chinese communist party likes to control and monitor people and likes to spy on people and imposes on Chinese companies to follow their orders, so is there a security risk when using opera proxy when for example the Chinese communist party orders opera to give out user passwords?

Any VPN company, Internet service provider or hosting provider may listen users traffic, regardless Chinese or not. Even European hosting providers follow such orders and even [actively interfere with service's traffic to perform man-in-the-middle attack](https://notes.valdikss.org.ru/jabber.ru-mitm/). However, in Opera case such traffic interception is kind of fruitless. Almost all sites are HTTPS now and they won't be able to perform decryption (unless they have TLS certs of that site or cooperating with them certificate authority). Without decryption all they can do is to learn visited domains and your connecting IP address. So I would say you're not risking your passwords more than usual.

> Another quetion please : hola -proxy has option " peer proxies on residental IPs (consumer ISP) ",
> 
> I read that the tuxler vpn
> 
> https://www.tuxlervpn.com/
> 
> allows us to use the real IP addresses of users and if a malicious user takes our IP address and does illegal activity, we can be punished and go to prison....is it the same thing with hola proxy when we use hola -proxy has option " peer proxies on residential IPs" ? hola proxy allows people to use our real ip address ?

Right now Hola forwards traffic of free users mostly through datacenter IP addresses because residential traffic is quite expensive. However in general Hola allows the use of residential IP addresses for some cases. Otherwise it will not be possible to access services with geo-restricted video content like Netflix or Hulu, which do not expect user to have datacenter IP address. Such IP sharing was a public concern and caused many complaints: http://adios-hola.org/

hola-proxy does not allow your IP to be used by others. It was specifically one of goals of such alternative implementation. Such function does not exists in hola-proxy and never will be.

**Comment by trimechee** [comment]
Ohhh very very interesting and useful information! Thanks a lot for your precious help and for all efforts to make many great awesome softwares 🥇 💯  !

We suggest that you put a pop-up window that launches automatically when we use one of your softwares to make easily a donation via paypal or buy me a coffee or bitcoin.....when we use one of your magnificent softwares so it will allow people who can makes donations to support these fantastic projects  and also display messages to encourage people to share your softwares on social networks like Twitter, Facebook, Snap....it will  give even more visibility to this amazing softwares....

I also suggest making a discussion section so you can include these important information and revelations that you so kindly made to me around the internal functioning of opera proxy, hola proxy.....in order to definitively answer any future questions and curiosity of users....thank you again very much for all your efforts to invent such useful softwares 🥇 !
